### ISSUE TITLE
self.operationTimeoutFn is not a function

### ISSUE THREAD

**Issue by matey-jack** [KhushrajRathod/retried#6]
Hey Khushraj, thanks for your nice library :smile: 

I think I found the following bug.

I adapted your example code as follows:

    function fetchWithRetry(url: string, opts: RequestInit): Promise<Response> {
        const ONE_SECOND = 1000;
        return new Promise((resolve, reject) => {
            const operation = retried.operation({minTimeout: ONE_SECOND})
            operation.attempt(async (currentAttempt: number) => {
                try {
                    resolve(await fetch(url, opts))
                } catch (error) {
                    console.error(`Attempt ${currentAttempt}, Error:`)
                    console.error(error)
    
                    if (await operation.retry(error)) return
                    reject(error)
                }
            })
        })
    }

And it gives this result:

    error: Uncaught TypeError: self.operationTimeoutFn is not a function
         self.operationTimeoutFn!(this.attempts)
                 ^
    at https://deno.land/x/retried@1.0.1/lib/retryOperation.ts:156:18
    at fire (deno:ext/timers/01_timers.js:477:7)
    at handleTimerMacrotask (deno:ext/timers/01_timers.js:338:7)

It looks to me like `operationTimeoutFn` in line 156 should be wrapped into a check like the one on line 101?

**Comment by alreadypro** [comment]
Also getting this error
